language: php

#services:
#  - mysql

#php:
#  - "7.2"
#  - "7.3"
#  - "7.4"
#  - nightly
#  - hhvm

jobs:
#  allow_failures:
#    - php: nightly
#    - php: hhvm
  include:
  - stage: 7.4
#    dist: xenial
    php: 7.4
    services:
      - mysql
#    sudo: required




install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - travis_retry composer require --no-update php-coveralls/php-coveralls
  - travis_retry composer install --no-interaction --prefer-dist --no-progress --no-suggest

script:
  - composer ci:test

after_success:
  - travis_retry php vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - travis_retry php vendor/bin/php-coveralls -v
