language: php

services:
  - mysql

#php:
#  - "7.2"
#  - "7.3"
#  - "7.4"
#  - nightly
#  - hhvm

jobs:
  #  allow_failures:
  #    - php: nightly
  #    - php: hhvm
  include:

    - stage: Test
      php: 7.1

    - stage: Test
      php: 7.2

    - stage: Test
      php: 7.3
      addons:
        mariadb: "10.4"

    - stage: Test
      php: 7.3

    - stage: Test
      php: 7.4
      script:
        - composer ci:test
      install:
        - travis_retry composer require --no-update php-coveralls/php-coveralls
        - travis_retry composer install --no-interaction --prefer-dist --no-progress --no-suggest
      after_success:
        - travis_retry php vendor/bin/phpunit --coverage-clover build/logs/clover.xml
        - travis_retry php vendor/bin/php-coveralls -v

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"

install:
  - travis_retry composer require phpunit/phpunit:7.5 --ignore-platform-reqs

script:
  - composer phpunit:test

